# This redirect rule is for your Single Page Application (SPA).
# It ensures that all paths are served by index.html so React Router can handle them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
